//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WkcCommunicator.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WkcCommunicator.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 License:  的本地化字符串。
        /// </summary>
        internal static string AppInfoView_License {
            get {
                return ResourceManager.GetString("AppInfoView_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string AppInfoView_OK {
            get {
                return ResourceManager.GetString("AppInfoView_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Repository 的本地化字符串。
        /// </summary>
        internal static string AppInfoView_ProjectRepository {
            get {
                return ResourceManager.GetString("AppInfoView_ProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol Version:  的本地化字符串。
        /// </summary>
        internal static string AppInfoView_ProtocolVersion {
            get {
                return ResourceManager.GetString("AppInfoView_ProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string AppInfoView_Title {
            get {
                return ResourceManager.GetString("AppInfoView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version:  的本地化字符串。
        /// </summary>
        internal static string AppInfoView_Version {
            get {
                return ResourceManager.GetString("AppInfoView_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Settings 的本地化字符串。
        /// </summary>
        internal static string AppShell_DeviceSettings {
            get {
                return ResourceManager.GetString("AppShell_DeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovery 的本地化字符串。
        /// </summary>
        internal static string AppShell_Discovery {
            get {
                return ResourceManager.GetString("AppShell_Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Device 的本地化字符串。
        /// </summary>
        internal static string AppShell_MyDevice {
            get {
                return ResourceManager.GetString("AppShell_MyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string DeleteView_Cancel {
            get {
                return ResourceManager.GetString("DeleteView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteView_Delete {
            get {
                return ResourceManager.GetString("DeleteView_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You’ll need to verify again after deleting. Delete it? 的本地化字符串。
        /// </summary>
        internal static string DeleteView_Warning {
            get {
                return ResourceManager.GetString("DeleteView_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Cancel {
            get {
                return ResourceManager.GetString("DeviceLabel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character:  的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Character {
            get {
                return ResourceManager.GetString("DeviceLabel_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Device 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_DeleteDevice {
            get {
                return ResourceManager.GetString("DeviceLabel_DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Disconnect {
            get {
                return ResourceManager.GetString("DeviceLabel_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer:  的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Manufacturer {
            get {
                return ResourceManager.GetString("DeviceLabel_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model:  的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Model {
            get {
                return ResourceManager.GetString("DeviceLabel_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Owner:  的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Owner {
            get {
                return ResourceManager.GetString("DeviceLabel_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol:  的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_ProtocolVersion {
            get {
                return ResourceManager.GetString("DeviceLabel_ProtocolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-verify 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Reverify {
            get {
                return ResourceManager.GetString("DeviceLabel_Reverify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please try again later 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_TryAgain {
            get {
                return ResourceManager.GetString("DeviceLabel_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Unknown&gt; 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_Unknown {
            get {
                return ResourceManager.GetString("DeviceLabel_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Unnamed Device&gt; 的本地化字符串。
        /// </summary>
        internal static string DeviceLabel_UnnamedDevice {
            get {
                return ResourceManager.GetString("DeviceLabel_UnnamedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legacy Settings 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_BasicInfo {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Character {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Connection {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Device 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_DeleteDevice {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_DeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Name 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_DeviceName {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Disconnect {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manufacturer 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Manufacturer {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Owner 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Owner {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unset 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Unset {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Unset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The next version of the protocol will stop reading settings entries directly from advertise data and will read the settings table from the characteristic instead. 的本地化字符串。
        /// </summary>
        internal static string DeviceSettingsPage_Warning {
            get {
                return ResourceManager.GetString("DeviceSettingsPage_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No device connected 的本地化字符串。
        /// </summary>
        internal static string DisconnectedSign_NoDeviceConnected {
            get {
                return ResourceManager.GetString("DisconnectedSign_NoDeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device security characteristic does not support update 的本地化字符串。
        /// </summary>
        internal static string MainPage_DeviceCommandUpdateNotSupported {
            get {
                return ResourceManager.GetString("MainPage_DeviceCommandUpdateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device connected 的本地化字符串。
        /// </summary>
        internal static string MainPage_DeviceConnected {
            get {
                return ResourceManager.GetString("MainPage_DeviceConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device not verified 的本地化字符串。
        /// </summary>
        internal static string MainPage_DeviceNotVerified {
            get {
                return ResourceManager.GetString("MainPage_DeviceNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device security characteristic does not support update. 的本地化字符串。
        /// </summary>
        internal static string MainPage_DeviceSecurityUpdateNotSupported {
            get {
                return ResourceManager.GetString("MainPage_DeviceSecurityUpdateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to connect device 的本地化字符串。
        /// </summary>
        internal static string MainPage_FailedToConnectDevice {
            get {
                return ResourceManager.GetString("MainPage_FailedToConnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read characteristics for verification 的本地化字符串。
        /// </summary>
        internal static string MainPage_FailedToReadCharacteristicsForVerification {
            get {
                return ResourceManager.GetString("MainPage_FailedToReadCharacteristicsForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read verification data 的本地化字符串。
        /// </summary>
        internal static string MainPage_FailedToReadVerificationData {
            get {
                return ResourceManager.GetString("MainPage_FailedToReadVerificationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to verify 的本地化字符串。
        /// </summary>
        internal static string MainPage_FailedToVerify {
            get {
                return ResourceManager.GetString("MainPage_FailedToVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Device 的本地化字符串。
        /// </summary>
        internal static string MainPage_MyDevice {
            get {
                return ResourceManager.GetString("MainPage_MyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nearby Device 的本地化字符串。
        /// </summary>
        internal static string MainPage_NearbyDevice {
            get {
                return ResourceManager.GetString("MainPage_NearbyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission not enabled 的本地化字符串。
        /// </summary>
        internal static string MainPage_PermissionNotEnabled {
            get {
                return ResourceManager.GetString("MainPage_PermissionNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved Device is null 的本地化字符串。
        /// </summary>
        internal static string MainPage_SavedDeviceIsNull {
            get {
                return ResourceManager.GetString("MainPage_SavedDeviceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keys 的本地化字符串。
        /// </summary>
        internal static string MyDevicePage_Keys {
            get {
                return ResourceManager.GetString("MyDevicePage_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string PairingView_Cancel {
            get {
                return ResourceManager.GetString("PairingView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Pass Key 的本地化字符串。
        /// </summary>
        internal static string PairingView_InputPassKey {
            get {
                return ResourceManager.GetString("PairingView_InputPassKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Unnamed Group&gt; 的本地化字符串。
        /// </summary>
        internal static string Table_UnnamedGroup {
            get {
                return ResourceManager.GetString("Table_UnnamedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Unnamed Option&gt; 的本地化字符串。
        /// </summary>
        internal static string Table_UnnamedOption {
            get {
                return ResourceManager.GetString("Table_UnnamedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Unnamed Property&gt; 的本地化字符串。
        /// </summary>
        internal static string Table_UnnamedProperty {
            get {
                return ResourceManager.GetString("Table_UnnamedProperty", resourceCulture);
            }
        }
    }
}
